package io.github.isan95.masivtest.db;

import io.github.isan95.masivtest.db.tables.Roulette;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {
    private static final long serialVersionUID = -1332522707;
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();
    public final Roulette ROULETTE = io.github.isan95.masivtest.db.tables.Roulette.ROULETTE;
    private DefaultSchema() {
        super("", null);
    }
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }
    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Roulette.ROULETTE);
    }
}
