package io.github.isan95.masivtest.db;
import io.github.isan95.masivtest.db.tables.Roulette;
import javax.annotation.Generated;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    private static class Indexes0 {
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Roulette.ROULETTE, new OrderField[] { Roulette.ROULETTE.ID }, true);
    }
}
