package io.github.isan95.masivtest.db;
import io.github.isan95.masivtest.db.tables.Roulette;
import io.github.isan95.masivtest.db.tables.records.RouletteRecord;
import javax.annotation.Generated;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {
    public static final Identity<RouletteRecord, Long> IDENTITY_ROULETTE = Identities0.IDENTITY_ROULETTE;
    public static final UniqueKey<RouletteRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    private static class Identities0 {
        public static Identity<RouletteRecord, Long> IDENTITY_ROULETTE = Internal.createIdentity(Roulette.ROULETTE, Roulette.ROULETTE.ID);
    }
    private static class UniqueKeys0 {
        public static final UniqueKey<RouletteRecord> CONSTRAINT_2 = Internal.createUniqueKey(Roulette.ROULETTE, "CONSTRAINT_2", Roulette.ROULETTE.ID);
    }
}
