package io.github.isan95.masivtest.db;
import io.github.isan95.masivtest.db.tables.Roulette;
import javax.annotation.Generated;
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {
    public static final Roulette ROULETTE = Roulette.ROULETTE;
}
