/*
 * This file is generated by jOOQ.
 */
package io.github.isan95.masivtest.db;


import io.github.isan95.masivtest.db.tables.Roulette;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ROULETTE</code>.
     */
    public static final Roulette ROULETTE = Roulette.ROULETTE;
}
